# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fe025d00a05c22691ce606774d319c3effe110f21e3bb2444c4a3a7e7b7773ec52d76997fac5d1b48c1ec06ac3efd8ad8297ebebcfac0c1d57147bdea3adb8

test:
  secret_key_base: cc891f271685477368dd0b5d2c265a8d6f361921ff9435029ff4065d139dcbedf25d1056af7dbeaf77fe758b9b2dd34a920ac16ff9c69d636119889c81033d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
